name = "youtube"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "YOUTUBE_OAUTH"
id = "fc63b203b5444239bcc7f1593ac00c9e"

[observability]
enabled = false
head_sampling_rate = 1
