name = "ms"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "MICROSOFT_OAUTH"
id = "1fc675ab17fc42cba0e6011f33f17b28"

[observability]
enabled = false
head_sampling_rate = 1
