name = "gmail"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "GMAIL_OAUTH"
id = "9f974caf49e540ef8c68069e8490f93a"

[observability]
enabled = false
head_sampling_rate = 1
