name = "gmail"
main = "index.js"
compatibility_date = "2024-12-01"
workers_dev = true
preview_urls = true

[[d1_databases]]
binding = "OAUTH_DB"
database_name = "gotoolkit-oauth"
database_id = "045c8946-c438-4846-871d-cd34b131266d"

[observability]
enabled = false
head_sampling_rate = 1
